<?php
/**
 * Attributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  DigitalRiver\ApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DigitalRiver\ApiSdk\Model;

use \ArrayAccess;
use \DigitalRiver\ApiSdk\ObjectSerializer;

/**
 * Attributes Class Doc Comment
 *
 * @category Class
 * @package  DigitalRiver\ApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Attributes implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Attributes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'invoice_title' => 'string',
        'reg_account' => 'string',
        'reg_address' => 'string',
        'reg_bank' => 'string',
        'reg_phone' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'invoice_title' => null,
        'reg_account' => null,
        'reg_address' => null,
        'reg_bank' => null,
        'reg_phone' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'invoice_title' => 'invoiceTitle',
        'reg_account' => 'regAccount',
        'reg_address' => 'regAddress',
        'reg_bank' => 'regBank',
        'reg_phone' => 'regPhone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'invoice_title' => 'setInvoiceTitle',
        'reg_account' => 'setRegAccount',
        'reg_address' => 'setRegAddress',
        'reg_bank' => 'setRegBank',
        'reg_phone' => 'setRegPhone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'invoice_title' => 'getInvoiceTitle',
        'reg_account' => 'getRegAccount',
        'reg_address' => 'getRegAddress',
        'reg_bank' => 'getRegBank',
        'reg_phone' => 'getRegPhone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['invoice_title'] = isset($data['invoice_title']) ? $data['invoice_title'] : null;
        $this->container['reg_account'] = isset($data['reg_account']) ? $data['reg_account'] : null;
        $this->container['reg_address'] = isset($data['reg_address']) ? $data['reg_address'] : null;
        $this->container['reg_bank'] = isset($data['reg_bank']) ? $data['reg_bank'] : null;
        $this->container['reg_phone'] = isset($data['reg_phone']) ? $data['reg_phone'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets invoice_title
     *
     * @return string|null
     */
    public function getInvoiceTitle()
    {
        return $this->container['invoice_title'];
    }

    /**
     * Sets invoice_title
     *
     * @param string|null $invoice_title The title of the invoice.
     *
     * @return $this
     */
    public function setInvoiceTitle($invoice_title)
    {
        $this->container['invoice_title'] = $invoice_title;

        return $this;
    }

    /**
     * Gets reg_account
     *
     * @return string|null
     */
    public function getRegAccount()
    {
        return $this->container['reg_account'];
    }

    /**
     * Sets reg_account
     *
     * @param string|null $reg_account The identifier for the account.
     *
     * @return $this
     */
    public function setRegAccount($reg_account)
    {
        $this->container['reg_account'] = $reg_account;

        return $this;
    }

    /**
     * Gets reg_address
     *
     * @return string|null
     */
    public function getRegAddress()
    {
        return $this->container['reg_address'];
    }

    /**
     * Sets reg_address
     *
     * @param string|null $reg_address The address associated to the invoice.
     *
     * @return $this
     */
    public function setRegAddress($reg_address)
    {
        $this->container['reg_address'] = $reg_address;

        return $this;
    }

    /**
     * Gets reg_bank
     *
     * @return string|null
     */
    public function getRegBank()
    {
        return $this->container['reg_bank'];
    }

    /**
     * Sets reg_bank
     *
     * @param string|null $reg_bank The name of the bank.
     *
     * @return $this
     */
    public function setRegBank($reg_bank)
    {
        $this->container['reg_bank'] = $reg_bank;

        return $this;
    }

    /**
     * Gets reg_phone
     *
     * @return string|null
     */
    public function getRegPhone()
    {
        return $this->container['reg_phone'];
    }

    /**
     * Sets reg_phone
     *
     * @param string|null $reg_phone The phone number associated to the invoice
     *
     * @return $this
     */
    public function setRegPhone($reg_phone)
    {
        $this->container['reg_phone'] = $reg_phone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


