<?php
/**
 * ChargeType
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  DigitalRiver\ApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DigitalRiver\ApiSdk\Model;
use \DigitalRiver\ApiSdk\ObjectSerializer;

/**
 * ChargeType Class Doc Comment
 *
 * @category Class
 * @description Represents the charge type.
 * @package  DigitalRiver\ApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChargeType
{
    /**
     * Possible values of this enum
     */
    const CUSTOMER_INITIATED = 'customer_initiated';
    const MERCHANT_INITIATED = 'merchant_initiated';
    const MOTO = 'moto';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        $allowable =  [
            self::CUSTOMER_INITIATED,
            self::MERCHANT_INITIATED,
            self::MOTO,
        ];
        $allowableAllCase = array_merge(array_map('strtolower', $allowable), $allowable);
        return $allowableAllCase;
    }
}


